name: Install Terraform & Terragrunt
description: ""

inputs:
  terragrunt-version:
    description: Terragrunt version
    required: true
  terraform-version:
    description: Terraform version
    required: true
outputs:
  terragrunt-version:
    description: The installed Terragrunt version
    value: ${{ inputs.terragrunt-version }}
  terraform-path:
    description: The path to the Terraform executable
    value: ${{ steps.tf-path.outputs.path }}

runs:
  using: composite
  steps:
    -
      name: Install Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
    -
      name: Identify Terraform path
      shell: bash
      id: tf-path
      run: |
        echo "::group::Identify Terraform path"

        TERRAFORM_BINARY=$(command -v terraform)
        echo "path=$TERRAFORM_BINARY" | tee -a "$GITHUB_OUTPUT"

        echo "::endgroup:;"
    -
      name: Install Terragrunt
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_version: ${{ inputs.terragrunt-version }}
        tf_path: ${{ steps.tf-path.outputs.path }}
    -
      name: Persist inputs for future calls
      shell: bash
      run: |
        # Persist inputs for future calls
        echo "TG_INSTALL_TG_VERSION=${{ inputs.terragrunt-version }}" >> "$GITHUB_ENV"
        echo "TG_INSTALL_TF_PATH=${{ steps.tf-path.outputs.path }}" >> "$GITHUB_ENV"
