name: PR Ready
description: Check that fails if any dependency failed

inputs:
  needs:
    description: Job dependencies this check must wait for.
    required: true

runs:
  using: composite
  steps:
    -
      name: Validate jobs
      shell: bash
      if: ${{ contains(fromJSON(inputs.needs).*.result, 'cancelled') || contains(fromJSON(inputs.needs).*.result, 'failure') }}
      run: |
        echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
        exit 1
