name: pr-infra

on:
  pull_request:
    paths:
      - 'infra/**'

permissions:
  contents: read
  id-token: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:

  lint:
    uses: ./.github/workflows/check-tf-modules.yml
    with:
      WORKING_DIR: infra
      MODULES_DIR: infra/modules
    secrets:
      GH_APP_CLIENT_ID: ${{ secrets.WRITER_APP_CLIENT_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.WRITER_APP_PRIVATE_KEY }}
